apiVersion: dev.crossplane.io/v1alpha1
kind: Project
metadata:
  name: configuration-aws-network-ts
spec:
  architectures:
  - amd64
  - arm64
  crossplane:
    version: '>=v2.0.0-0'
  dependencies:
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Provider
      package: xpkg.upbound.io/upbound/provider-aws-ec2
      version: '>=v2.7.0'
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: '>=v0.7.0'
  - k8s:
      version: v1.33.0
    type: k8s
  description: |
    This configuration provides a foundation to build and operate AWS networks.
  license: Apache-2.0
  maintainer: Upbound <support@upbound.io>
  readme: |
    This configuration is used for deploying and managing AWS networks on
    Kubernetes using Crossplane. The composition logic is written in
    TypeScript as an embedded composition function.

    For more details and customization options, you can explore
    [the GitHub repository](https://github.com/upbound/configuration-aws-network-ts).
  repository: xpkg.upbound.io/upbound/configuration-aws-network-ts
  schemas:
    languages:
    - typescript
  source: github.com/upbound/configuration-aws-network-ts
