apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: networks.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: Network
  mode: Pipeline
  pipeline:
  - step: network
    functionRef:
      name: upbound-configuration-aws-network-tsnetwork
  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
